import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useState } from "react";
import Form from "./components/form";

export default function Home() {
  const [answer, setAnswer] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center gap-4 px-8 text-center">
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <Form answer={answer} setAnswer={setAnswer} />
        {answer && <div>{answer}</div>}
      </main>
    </>
  );
}
